### ISSUE TITLE
Changing browser tabs while adding a new spot details, resets to previous spot GPS mark

### ISSUE THREAD

**Issue by katesclau** [RafalWilinski/wildspot#1]
This causes the new spot to be saved in the previous spot GPS mark.

**Steps to reproduce:**
1. Click add
2. Choose the location
3. Add some details
4. Change tab
5. Change back
7. Save

**Expected Result**
Spot is added in the user defined placement

**Result**
Spot is saved in same place as last added spot.

**Comment by RafalWilinski** [comment]
Thanks for reporting this issue @katesclau! Going to fix that asap.

**Comment by RafalWilinski** [comment]
Fixed
